package ${package};

import lombok.*;

import java.time.Instant;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ApiErrorResponse {

    private Instant timestamp;

    private int status;

    private String error;

    private String message;

    private String path;

}