package ${package};

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
public class BusinessException
        extends RuntimeException {

    public BusinessException(String message) {

        super(message);

    }

}