package ${package};

import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@RestController
@RequiredArgsConstructor
@RequestMapping("${requestMapping}")
public class ${className} {

    private final ${useCase} ${useCaseField};

    @${mappingAnnotation}Mapping
    public ResponseEntity<${responseType}> execute(
            @RequestBody ${requestType} request) {

        return ResponseEntity.ok(
                ${useCaseField}.execute(request));

    }

}