package ${package};

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@Service
@RequiredArgsConstructor
public class ${className} {

${methods}

}