package ${package};

import lombok.*;

import java.io.Serializable;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
public class ${className} implements Serializable {

    private static final long serialVersionUID = 1L;

${fields}

}