package ${package};

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@Component
@RequiredArgsConstructor
public class ${className} {

${methods}

}