package ${package};

import ${entityPackage}.${entityClass};
import ${dtoPackage}.${dtoClass};

import org.mapstruct.Mapper;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@Mapper(componentModel = "spring")
public interface ${className} {

    ${dtoClass} toDto(${entityClass} entity);

    ${entityClass} toEntity(${dtoClass} dto);

}