package ${package};

import org.springframework.stereotype.Component;

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
@Component
public class ${className} {

${methods}

}