package ${package};

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
public class ResourceNotFoundException
        extends RuntimeException {

    public ResourceNotFoundException(String message) {

        super(message);

    }

}