package ${package};

import ${package.replace(".specification", ".entity")}.${targetEntity};

/**
 * --------------------------------------------------------------------
 * AUTO-GENERATED BY ASEP
 * DO NOT MODIFY MANUALLY.
 * --------------------------------------------------------------------
 */
public class ${className} {

    public boolean isSatisfiedBy(${targetEntity} candidate) {

        throw new UnsupportedOperationException(
                "Generated specification - implementation pending.");

    }

}